import type { Metadata } from "next"
import { cookies } from "next/headers"

import "./globals.css"

import { DarkModeProvider } from "@/providers/dark-mode-provider"
import { ThemeProvider } from "@/providers/theme-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const theme = cookieStore.get("theme")?.value

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased ${theme ? `theme-${theme}` : ""}`}>
        <DarkModeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ThemeProvider initialTheme={theme}>{children}</ThemeProvider>
        </DarkModeProvider>
      </body>
    </html>
  )
}
